stages:
  train:
    foreach: ${models} # top level object (dict) from params.yaml
    do:
      cmd: python src/train.py ${key} data/${item.data} # key: item - key and object values from dict
      deps:
      - src/train.py
      - data/${item.data}
      outs:
      - models/${key}
  eval:
    foreach: ${models}
    do:
      cmd: python src/eval.py ${key} data/${item.data}
      deps:
      - src/eval.py
      - models/${key}

artifacts:
  model1:
    path: models/model1
    type: model
    desc: Model description for model1
    labels:
    - xgboost
  model2:
    path: models/model2
    type: model
    desc: Model description for model2
    labels:
    - xgboost
  model3:
    path: models/model3
    type: model
    desc: Model description for model3
    labels:
    - xgboost
metrics:
- dvclive/model1/metrics.json
- dvclive/model2/metrics.json
- dvclive/model3/metrics.json
- dvclive/train/model1/metrics.json
- dvclive/train/model2/metrics.json
- dvclive/train/model3/metrics.json
- dvclive/eval/model1/metrics.json
- dvclive/eval/model2/metrics.json
- dvclive/eval/model3/metrics.json
